### ISSUE TITLE
Learning Error Mistral

### ISSUE THREAD

**Issue by nikitabalakin** [FartyPants/Training_PRO#5]
Traceback (most recent call last):
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\gradio\queueing.py", line 406, in call_prediction
    output = await route_utils.call_process_api(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1554, in process_api
    result = await self.call_function(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\gradio\blocks.py", line 1206, in call_function
    prediction = await utils.async_iteration(iterator)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 517, in async_iteration
    return await iterator.__anext__()
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 510, in __anext__
    return await anyio.to_thread.run_sync(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 493, in run_sync_iterator_async
    return next(iterator)
  File "E:\text-generation-webui\installer_files\env\lib\site-packages\gradio\utils.py", line 647, in gen_wrapper
    yield from f(*args, **kwargs)
  File "E:\text-generation-webui\extensions\Training_PRO\script.py", line 708, in do_train
    target_modules=model_to_lora_modules[model_id],
KeyError: 'mistral'

**Comment by FartyPants** [comment]
That had been fixed at some point - you need to get the latest version from here

**Comment by nikitabalakin** [comment]
understood, can you please tell me how to do it?
